/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://h6a22o5ohvfolmuefnvu4rs22q.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_cognito_identity_pool_id": "us-east-2:c873ba2b-9396-433a-bb7e-4f3ab9931958",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_IkvcuuRLI",
    "aws_user_pools_web_client_id": "58ria27h3rrehc22kmc09niuk6",
    "oauth": {},
    "aws_user_files_s3_bucket": "linkedinlearningrunt8767d3b1ff404f5fb0f3f2163f5212735-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
