/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5r5cdzc4m5ghjcchytqdxrpje4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_cognito_identity_pool_id": "us-east-1:5378ac10-f65d-47b3-bb95-a5ba761cbe8a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TAIyI3L3T",
    "aws_user_pools_web_client_id": "5ojmhod115t60d5chv1l0dhouu",
    "oauth": {},
    "aws_user_files_s3_bucket": "linkedinlearningampl1b44920422604425bcfe144b0a0191651-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
